### ISSUE TITLE
404 for certain resources

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-ui#307]
There seem to be two issues with [this regex rule](https://github.com/inmanta/inmanta-ui/blob/135c525758cf9a1ccd46cefffdb9d41777d90135/src/inmanta_ui/ui.py#L83), the first with a reproduction, the other just speculation:
- [x] http://mgmt.ii.inmanta.com:8888/console/resources/exec%3A%3ARun[longevity-2022.1.ii.inmanta.com] is a valid resource specification, yet it results in a 404. When you [drop the `.com`](http://mgmt.ii.inmanta.com:8888/console/resources/exec%3A%3ARun[longevity-2022.1.ii.inmanta]) it doesn't result in a 404. I believe the issue here is that because of `\.[^\s]{2,5}` it is assumed this is a reference to a file, which it is in fact not.
- [x] The rule contains `[^\s]` which looks like an attempt to disallow spaces. Within a `[^...]` I don't think `\s` is supported though. So instead we're disallowing backslashes and the character "s". This still needs to be confirmed.

Go with alphanum instead.

**Comment by Hugo-Inmanta** [comment]
Regarding bullet point n°2, it seems like `\s` is supported within `[^...]` :
```python39
import re

pattern = r"([^\s])"
regex = re.compile(pattern)

positive_examples = [
    "dd",
    "\\",
    "s",
    ]
negative_examples = [
    " ",
    "\n",
    "\t",
    ]

for ex in positive_examples:
    match = regex.match(ex)
    assert match

for ex in negative_examples:
    match = regex.match(ex)
    assert not match
```
