### ISSUE TITLE
Add web-ui section to the configuration file

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-ui#317]
There are currently two issues with the configuration options of the web-console:

* First of all, not all options are part of the same section. All authentication-related options are present in the old `dashboard` section. All other options, like whether the dashboard is enabled or not, is part of the `web-console` section.
* Secondly, the name of the config section of the web-console is too application specific. As such, we have to create a new configuration section every time we introduce a new web-interface.

Tasks:

- [x] Create a new section `web-ui`. This section will contain all config options that are currently part of the `web-console` and the `dashboard` section.
- [ ] Keep the `web-console` and the `dashboard` section, but log a deprecation warning when it's used and mention that the `web-ui` section should be used instead.

Add deprecation note in iso5, drop support in iso6 (with changelog note).

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-ui/317?planning-poker) with Zenhub @arnaudsjs @FloLey @Hugo-Inmanta @sanderr

**Comment by Hugo-Inmanta** [comment]
PRs for iso6:
- https://github.com/inmanta/inmanta-core/pull/5046
- https://github.com/inmanta/inmanta-ui/pull/327

**Comment by Hugo-Inmanta** [comment]
PRs for iso5:
- https://github.com/inmanta/inmanta-core/pull/5077
- https://github.com/inmanta/inmanta-ui/pull/330
